### ISSUE TITLE
Missing Guava refactor rules for static methods

### ISSUE THREAD

**Issue by twicksell** [atomist/sdm-pack-api-usage-fingerprinting#8]
It looks like static methods like ` Objects.firstNonNull` -> `MoreObjects.firstNonNull` are missing from the refactors for guava.

**Comment by lievendoclo** [comment]
Added functionality, see #9 , will however replace with fully qualified classname for now, as there are a couple of variants (wildcard static imports, static imports, ...) that make adding imports for that specific class tricky. Adding the FQN reference is the safest option in this case.
